### ISSUE TITLE
flask_study

### ISSUE THREAD

**Issue by johntoms** [techstay/python-study#1]
learn flask first in 2018/2/25

**Comment by johntoms** [comment]
from flask import Flask
from flask import request

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def home():
    return '<h1>Home</h1>'

@app.route('/signin', methods=['GET'])
def signin_form():
    return '''<form action="/signin" method="post">
              <p><input name="username"></p>
              <p><input name="password" type="password"></p>
              <p><button type="submit">Sign In</button></p>
              </form>'''

@app.route('/signin', methods=['POST'])
def signin():
    # 需要从request对象读取表单内容：
    if request.form['username']=='admin' and request.form['password']=='password':
        return '<h3>Hello, admin!</h3>'
    return '<h3>Bad username or password.</h3>'

if __name__ == '__main__':

**Comment by techstay** [comment]
Hello, do you have any trouble I can help you? What you post is wrong formated so I'm puzzled.
