### ISSUE TITLE
如何将项目部署到linux服务器呢？

### ISSUE THREAD

**Issue by AIM-1993** [techstay/python-study#2]
你好，我是一名初学者，请问如何将完成的flask项目部署到自己的linux服务器主机呢？谢谢！

**Comment by techstay** [comment]
先在linux服务器上安装好Python和那些包，然后复制过去用命令行运行就行了

**Comment by AIM-1993** [comment]
> 先在linux服务器上安装好Python和那些包，然后复制过去用命令行运行就行了

 谢谢！我想尝试用nginx + unicorn部署一个flask项目，但是怎样让网站的url能够像www.xxxx.com这样被公网访问呢？

**Comment by techstay** [comment]
你服务器应该有公网ip，然后你需要去阿里云、腾讯云或者国外的域名商去买域名，这些域名商一般会附带DNS服务，你购买之后就可以在她们的网站上把域名绑定到你ip上。当然国内的域名还需要备案才能使用。

**Comment by AIM-1993** [comment]
非常感谢回复！目前我在尝试学习用heroku和unicorn进行部署，但是困惑的是在git push heroku master这一步的时候报错了，起先提示'No default language could be detected for this app',就按官网指导set了heroku/Python，但是又提示buildpack不适配App，不知你有没有这方面的解决办法啊？谢谢！

过了即是客 <notifications@github.com>编写：

**Comment by techstay** [comment]
我弄了一下heroku，发现[python教程](https://devcenter.heroku.com/articles/getting-started-with-python)里面需要pipenv，然后我克隆了一下官方教程里面的示例项目，发现果然如此。

所以你安装pipenv并把项目依赖项添加进去就好了：
``` shell
pip install pipenv
pipenv install flask #你项目用到什么包，就在这里都加进去
```
然后就能上传上去了

**Comment by AIM-1993** [comment]
> 
> 
> 我弄了一下heroku，发现[python教程](https://devcenter.heroku.com/articles/getting-started-with-python)里面需要pipenv，然后我克隆了一下官方教程里面的示例项目，发现果然如此。
> 
> 所以你安装pipenv并把项目依赖项添加进去就好了：
> 
> ```shell
> pip install pipenv
> pipenv install flask #你项目用到什么包，就在这里都加进去
> ```
> 
> 然后就能上传上去了

恩，确实如此，需要在项目顶级目录（包括虚拟环境在内）下推送，今天也是这样顺利把代码push上去了，但是目前困惑怎样连接postgres数据库，，，根据网上的资料显示将数据库的URI配置为DATABASE_URL这个变量，并安装addons就好了，但是按照这样配置并推送后，deploy的时候报错说DATABASE_URL变量未定义。请问这还需要一些其他配置吗？

**Comment by techstay** [comment]
这就不清楚了，我对heroku也没啥了解，刚看了一下文档，这方面懂得可能还不如你多，还得你自己来研究。
